BINANCE_STABLECOINS = {"USDT", "USDC", "BUSD", "FDUSD"}
QUALITY_SCORE_BINANCE = 90
BINANCE_MARKET = "binance"
BINANCE_SOURCE = "binance"
BINANCE_PRICE_SOURCE = "binance_api"
BINANCE_PRICE_VENUE = "BINANCE"
