from backend.core.settings import (
    SSM_ENV_NAME_PATTERN,
    SSM_ENV_OVERRIDE_VAR,
    SSM_ENV_PATH_VAR,
    Settings,
    _env_as_bool,
    _load_ssm_environment,
    load_settings,
    short_account_id,
)

settings = load_settings()

DEFAULT_BINANCE_BASE_URL = settings.DEFAULT_BINANCE_BASE_URL
DEFAULT_BINANCE_RECV_WINDOW_MS = settings.DEFAULT_BINANCE_RECV_WINDOW_MS
DEFAULT_JWT_EXPIRES_MINUTES = settings.DEFAULT_JWT_EXPIRES_MINUTES
DEFAULT_PPI_API_VERSION = settings.DEFAULT_PPI_API_VERSION

OUTPUT_DIR = settings.OUTPUT_DIR
S3_BUCKET = settings.S3_BUCKET
S3_PREFIX = settings.S3_PREFIX

IOL_USERNAME = settings.IOL_USERNAME
IOL_PASSWORD = settings.IOL_PASSWORD

PPI_PUBLIC_API_KEY = settings.PPI_PUBLIC_API_KEY
PPI_PRIVATE_API_KEY = settings.PPI_PRIVATE_API_KEY
PPI_ACCOUNT_NUMBER = settings.PPI_ACCOUNT_NUMBER
PPI_API_VERSION = settings.PPI_API_VERSION
ENABLE_PPI = settings.ENABLE_PPI
PPI_SANDBOX = settings.PPI_SANDBOX

ACCOUNT_EMAIL = settings.ACCOUNT_EMAIL
ACCOUNT_ID = settings.ACCOUNT_ID

SANTANDER_HOLDINGS_FILE = settings.SANTANDER_HOLDINGS_FILE
CRYPTO_HOLDINGS_FILE = settings.CRYPTO_HOLDINGS_FILE

BINANCE_API_KEY = settings.BINANCE_API_KEY
BINANCE_API_SECRET = settings.BINANCE_API_SECRET
BINANCE_BASE_URL = settings.BINANCE_BASE_URL
BINANCE_RECV_WINDOW_MS = settings.BINANCE_RECV_WINDOW_MS
ENABLE_BINANCE = settings.ENABLE_BINANCE
BINANCE_BALANCE_LAMBDA = settings.BINANCE_BALANCE_LAMBDA

ETHERSCAN_API_KEY = settings.ETHERSCAN_API_KEY
ETHEREUM_WALLET_ADDRESSES = settings.ETHEREUM_WALLET_ADDRESSES
ETHEREUM_TOKEN_CONTRACTS = settings.ETHEREUM_TOKEN_CONTRACTS
ENABLE_ETHEREUM = settings.ENABLE_ETHEREUM

EXODUS_ETH_ADDRESSES = settings.EXODUS_ETH_ADDRESSES
EXODUS_BTC_ADDRESSES = settings.EXODUS_BTC_ADDRESSES
ENABLE_EXODUS = settings.ENABLE_EXODUS

METAMASK_BTC_ADDRESSES = settings.METAMASK_BTC_ADDRESSES
ENABLE_METAMASK_BTC = settings.ENABLE_METAMASK_BTC

BLOCKCYPHER_API_KEY = settings.BLOCKCYPHER_API_KEY

JWT_SECRET = settings.JWT_SECRET
DEMO_AUTH_USERNAME = settings.DEMO_AUTH_USERNAME
DEMO_AUTH_PASSWORD = settings.DEMO_AUTH_PASSWORD
JWT_EXPIRES_MINUTES = settings.JWT_EXPIRES_MINUTES
