version: "3.9"

services:
  backend:
    image: 875551125619.dkr.ecr.us-east-1.amazonaws.com/fintracker-backend:latest
    env_file:
      - backend/.env
    container_name: fintracker-backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    image: 875551125619.dkr.ecr.us-east-1.amazonaws.com/fintracker-frontend:latest
    container_name: fintracker-frontend
    restart: unless-stopped
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: fintracker-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
